services:
  database:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
