services:
  database:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
  
  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: always
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "uvicorn"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & 
             sleep 5 && 
             curl -s http://localhost:8000/ > /dev/null && 
             tail -f /dev/null"

volumes:
  db_data:
