services:
  database:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      - DATABASE_URL=mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      - WDS_SOCKET_PORT=0 # Required for HMR to work through Docker
    networks:
      - app-network
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:5173" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
