from app.models import Base
from sqlalchemy import Column, Integer, String, Text, Float, ForeignKey, Date

class Stamp(Base):
    __tablename__ = "stamps"

    stampid = Column(Integer, primary_key=True, autoincrement=True)
    number = Column(String(255))
    type = Column(String(255))
    denomination = Column(String(255))
    color = Column(String(255))
    description = Column(Text)
    stamps_issued = Column(String(255))
    mint_condition = Column(String(255))
    unused = Column(String(255))
    used = Column(String(255))
    letter_fdc = Column(String(255))
    date_of_issue = Column(Date)
    perforations = Column(String(255))
    sheet_size = Column(String(255))
    designed = Column(String(255))
    engraved = Column(String(255))
    height_width = Column(String(255))
    image_accuracy = Column(Integer)
    perforation_horizontal = Column(Float)
    perforation_vertical = Column(Float)
    perforation_keyword = Column(String(2083))
    value_from = Column(Float)
    value_to = Column(Float)
    number_issued = Column(Integer)
    mint_condition_float = Column(Float)
    unused_float = Column(Float)
    used_float = Column(Float)
    letter_fdc_float = Column(Float)
    sheet_size_amount = Column(Float)
    sheet_size_x = Column(Float)
    sheet_size_y = Column(Float)
    sheet_size_note = Column(String(2083))
    height = Column(Float)
    width = Column(Float)
    setid = Column(Integer, ForeignKey("sets.setid", ondelete="CASCADE"))
